export const fechasImportantes = [
  { "month": 0, "day": 1, "label": "Año Nuevo", "type": "festivo" },
  { "month": 1, "day": 5, "label": "Día de la Constitución", "type": "noLaborable" },
  { "month": 1, "day": 24, "label": "Día de la Bandera", "type": "conmemoracion" },
  { "month": 2, "day": 13, "label": "Fundación de Tenochtitlán", "type": "conmemoracion" },
  { "month": 2, "day": 18, "label": "Expropiación Petrolera", "type": "conmemoracion" },
  { "month": 2, "day": 21, "label": "Natalicio Benito Juárez", "type": "noLaborable" },
  { "month": 2, "day": 22, "label": "Día Mundial del Agua", "type": "evento" },
  { "month": 3, "day": 10, "label": "Muerte de Emiliano Zapata", "type": "conmemoracion" },
  { "month": 3, "day": 30, "label": "Día del Niño", "type": "evento" },
  { "month": 4, "day": 1, "label": "Día del Trabajo", "type": "festivo" },
  { "month": 4, "day": 5, "label": "Batalla de Puebla", "type": "conmemoracion" },
  { "month": 4, "day": 8, "label": "Natalicio de Miguel Hidalgo", "type": "conmemoracion" },
  { "month": 4, "day": 10, "label": "Día de la Madre", "type": "evento" },
  { "month": 4, "day": 15, "label": "Día del Maestro", "type": "evento" },
  { "month": 5, "day": 1, "label": "Día de la Marina", "type": "conmemoracion" },
  { "month": 5, "day": 5, "label": "Natalicio de Francisco Villa", "type": "conmemoracion" },
  { "month": 5, "day": 5, "label": "Día Mundial del Medio Ambiente", "type": "evento" },
  { "month": 5, "day": 7, "label": "Día de la Libertad de Expresión", "type": "evento" },
  { "month": 7, "day": 8, "label": "Natalicio de Emiliano Zapata", "type": "conmemoracion" },
  { "month": 7, "day": 9, "label": "Día Pueblos Indígenas", "type": "evento" },
  { "month": 7, "day": 10, "label": "Natalicio de Vicente Guerrero", "type": "conmemoracion" },
  { "month": 7, "day": 13, "label": "Caída de Tenochtitlán", "type": "conmemoracion" },
  { "month": 8, "day": 1, "label": "Informe Presidencial", "type": "evento" },
  { "month": 8, "day": 13, "label": "Día de los Niños Héroes", "type": "conmemoracion" },
  { "month": 8, "day": 16, "label": "Día de la Independencia", "type": "festivo" },
  { "month": 8, "day": 27, "label": "Consumación de la Independencia", "type": "conmemoracion" },
  { "month": 8, "day": 30, "label": "Natalicio de José María Morelos", "type": "conmemoracion" },
  { "month": 9, "day": 2, "label": "Aniv. Movimiento Estudiantil 1968", "type": "conmemoracion" },
  { "month": 9, "day": 12, "label": "Día de la Raza", "type": "conmemoracion" },
  { "month": 9, "day": 24, "label": "Día de las Naciones Unidas", "type": "evento" },
  { "month": 9, "day": 30, "label": "Natalicio de Francisco I. Madero", "type": "conmemoracion" },
  { "month": 10, "day": 2, "label": "Día de Muertos", "type": "evento" },
  { "month": 10, "day": 20, "label": "Aniv. Revolución Mexicana", "type": "festivo" },
  { "month": 11, "day": 25, "label": "Navidad", "type": "festivo" },
  { "month": 11, "day": 31, "label": "Fin de Año", "type": "evento" }
];
